plugins {
    id 'com.android.application'
}

android {
    namespace 'com.birgsol.ai'
    compileSdk 34

    defaultConfig {
        applicationId 'com.birgsol.ai'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '3.5'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
